/* ══════════════════════════════════════════════════════════════════════
   Liburuen koadernoa · hojas de respuestas de «Arian A1» (ikaslearen liburua)
   ----------------------------------------------------------------------
   Para trabajar el libro desde la app SIN copiarlo. De cada ejercicio se
   guarda solo lo que hace falta para contestar:
     · su número, su página y la pista de audio;
     · qué casillas tiene (cuántas, de qué tipo) y qué trae ya resuelto.
   No hay enunciados, diálogos, lecturas ni cuadros de gramática: se leen
   en el libro. Por eso este fichero se puede publicar.
   Lo que sí es texto es propio (⚠ Claude): la nota de cada apartado («lan»,
   qué se trabaja y dónde está en Geruzak) y la descripción de cada ejercicio.
   Los títulos de apartado («g») son los rótulos del libro, para localizarlos.
   Las soluciones van aparte, en arian-a1-erantzunak.js.
   Formato y tipos de casilla: orriak.js.
   Las claves de lo escrito salen de «id» de unidad + apartado + número +
   rótulo: si se corrige una hoja, no cambiar los rótulos ya publicados.
   ══════════════════════════════════════════════════════════════════════ */
(function(){
  /* rótulos seguidos: L(1,6) → '1'…'6' · L('a','e') → 'a'…'e' */
  function L(a, b){
    var o = [], i;
    if (typeof a === 'number') for (i = a; i <= b; i++) o.push(String(i));
    else for (i = a.charCodeAt(0); i <= b.charCodeAt(0); i++) o.push(String.fromCharCode(i));
    return o;
  }
  var ABC = ['A', 'B', 'C'], P2 = ['1.ª', '2.ª'], P3 = ['1.ª', '2.ª', '3.ª'], P4 = ['1.ª', '2.ª', '3.ª', '4.ª'], BE = ['Bai', 'Ez'], EG = ['E', 'G'];
  var GOGORATU = 'Gogoratu · tus notas de repaso';
  var BIETAKO = 'En el libro se subraya; aquí marcas cuál de las dos.';
  var EGIA = 'Egia ala gezurra · verdadero o falso';
  function ZENB(n){ return 'Vale el número de la palabra (1–' + n + ') o la palabra.'; }
  function LETRA(z){ return 'Escribe la letra de la frase (a–' + z + ').'; }
  function ADITZ(z){ return 'Escribe la letra del verbo (a–' + z + ').'; }
  function ESALDI(n){ return 'Escribe el número de la frase (1–' + n + ').'; }

  var U = [];

  /* ── 1 · Elkar ezagutzen (13–35) ─────────────────────────────────────── */
  U.push({ id:'aro-01', n:1, eu:'Elkar ezagutzen', orr:'13–35', atalak:[
    { id:'At', k:'Atarian', orr:'14–17',
      lan:'Saludos, despedidas y respuestas de cortesía. Presentarse con *izan*: **ni … naiz**, **zu … zara**; para negar, **ez naiz**.',
      lot:[[9, 'IZAN'], [15, 'La negación y el partitivo']],
      ar:[ { g:'Agurrak' },
        { n:'1', p:14, au:'1–4', m:'ikus', zer:'Entzun · escucha y fíjate en las palabras marcadas' },
        { n:'2', p:15, m:'abc', it:L(1,12), op:['Hasierakoa', 'Bukaerakoa', 'Erantzuna'], zabal:true, pre:{ '1':'Hasierakoa', '2':'Bukaerakoa', '3':'Erantzuna' },
          zer:'Sailkatu · saludo, despedida o respuesta', hint:'Una fila por expresión, en el orden de la tabla del libro.' },
        { n:'3', p:15, m:'tx', it:L('a','h'), pre:{ g:true }, zer:'Osatu · con las palabras del recuadro', hint:ZENB(8) },
        { g:'Aurkezpenak' },
        { n:'4', p:16, m:'tx', it:L('a','k'), zer:'Osatu · con las palabras del recuadro', hint:ZENB(5) },
        { n:'5', p:17, m:'tx', it:L('a','c'), zabal:true, zer:'Osatu · con las palabras del recuadro', hint:'Tres palabras en cada hueco.' },
        { n:'G', p:17, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'18–23',
      lan:'Presentar a otros y decir a qué se dedican: **hau / hori / hura** y **hauek / horiek / haiek**, *ala* para preguntar entre dos opciones, y las profesiones con **-a / -ak**.',
      lot:[[4, 'Hau, hori, hura'], [3, 'El sintagma nominal'], [9, 'IZAN']],
      ar:[ { g:'Lankideak' },
        { n:'1', p:18, au:'5', m:'tx', it:L('a','c'), zabal:true, zer:'Entzun eta osatu · con las palabras del recuadro', hint:'En la a, un hueco; en la b, dos; en la c, uno.' },
        { n:'2', p:18, au:'6', m:'tx', it:['b', 'c'], zabal:true, zer:'Entzun eta osatu · con las palabras del recuadro', hint:'La a viene resuelta. Dos huecos en la b y dos en la c.' },
        { n:'3', p:19, m:'tx', it:L('a','e'), luze:true, adib:true },
        { g:'Lagunak' },
        { n:'4', p:19, au:'7', m:'abc', it:L('a','e'), op:L(1,5), zabal:true, pre:{ a:'2' }, zer:'Lotu · cada persona con su trabajo' },
        { n:'5', p:20, m:'eg', it:L('a','d'), adib:true },
        { g:'Ikaskideak' },
        { n:'6', p:20, m:'tx', it:L('a','h'), zabal:true, pre:{ b:true }, zer:'Lotu · una profesión del recuadro para cada dibujo' },
        { n:'7', p:21, m:'tx', it:L('a','e'), luze:true, adib:true },
        { g:'Gazteak' },
        { n:'8', p:21, au:'8', m:'tx', it:L('a','g'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(7) },
        { n:'9', p:22, m:'tx', it:L('a','c'), luze:true, adib:true },
        { g:'Boluntarioak' },
        { n:'10', p:22, pp:'22–23', m:'abc', it:L(1,10), pre:{ '1':'a' } },
        { n:'11', p:23, m:'tx', it:L('a','d'), luze:true, adib:true },
        { n:'G', p:23, m:'tx', it:L(1,8), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'24–28',
      lan:'Decir quién es quién y de dónde es: nombre + demostrativo (**mutil hau**), la partícula **al** en las preguntas y **nongoa** (-koa, -goa, -ekoa).',
      lot:[[4, 'Hau, hori, hura'], [8, 'Los interrogativos'], [6, 'Los casos']],
      ar:[ { g:'Txangoan' },
        { n:'1', p:24, au:'9', m:'tx', it:L('a','i'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(9) },
        { n:'2', p:25, pp:'24–25', m:'eg', it:L('a','f'), adib:true },
        { g:'Kalean' },
        { n:'3', p:25, au:'10', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'4', p:26, m:'tx', it:L('a','e'), luze:true, adib:true },
        { g:'Unibertsitatean' },
        { n:'5', p:26, au:'11', m:'abc', it:L('a','e'), op:P2, zer:'Entzun · la primera o la segunda opción', hint:BIETAKO },
        { n:'6', p:27, m:'tx', it:L('a','e'), zabal:true, adib:true },
        { n:'7', p:27, m:'tx', it:L('a','f'), luze:true, adib:true },
        { g:'Kanpinean' },
        { n:'8', p:28, pp:'27–28', m:'abc', it:L(1,10), pre:{ '1':'b' } },
        { n:'G', p:28, m:'tx', it:L(1,6), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'29–33',
      lan:'Dar y pedir datos personales: dónde vives (**non** → -n, -en; *bizi izan*), la dirección, el teléfono y los números del 0 al 10.',
      lot:[[6, 'Los casos'], [17, 'Números, hora y calendario'], [9, 'IZAN']],
      ar:[ { g:'Udalekuetan' },
        { n:'1', p:29, m:'ikus', zer:'Irakurri · lee las fichas, con el vocabulario del margen' },
        { n:'2', p:30, au:'12', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'3', p:30, m:'eg', it:L('a','e'), adib:true },
        { g:'Erreklamazioetan' },
        { n:'4', p:31, pp:'30–31', au:'13', m:'tx', it:['a', 'b'], luze:true, zer:'Entzun eta osatu · los números, con letra', hint:'En la a, ocho cifras; en la b, diez.' },
        { g:'Jardunaldietan' },
        { n:'5', p:31, pp:'31–32', au:'14', m:'tx', it:L('a','h'), pre:{ a:true, b:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(8) },
        { n:'6', p:32, m:'tx', it:L('a','h'), luze:true, adib:true },
        { g:'Ibilgailuen azterketa teknikoan (IAT)' },
        { n:'7', p:32, pp:'32–33', m:'abc', it:L(1,8), pre:{ '1':'a' } },
        { n:'G', p:33, m:'tx', it:L(1,5), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'34',
      lan:'Práctica de toda la unidad: escribir la pregunta que corresponde a cada respuesta, rellenar una ficha con tus datos y presentarte por escrito.',
      ar:[
        { n:'1', p:34, m:'tx', it:L('a','l'), luze:true, zer:'Idatzi · la pregunta de cada respuesta' },
        { n:'2', p:34, m:'tx', it:L(1,11), zabal:true, zer:'Idatzi · tus datos personales', hint:'Once datos, en el orden de la ficha del libro.' },
        { n:'3', p:34, m:'idaz', zer:'Idazlana · tu presentación' } ] },
    { id:'Bd', k:'Badakizu?', orr:'35',
      lan:'Autoevaluación de la unidad: siete puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:35, m:'bai', it:L(1,7) } ] }
  ] });

  /* ── 2 · Non dago? (37–60) ───────────────────────────────────────────── */
  U.push({ id:'aro-02', n:2, eu:'Non dago?', orr:'37–60', atalak:[
    { id:'At', k:'Atarian', orr:'38–41',
      lan:'Los lugares de la ciudad y dónde está cada uno: **non** en nombres comunes (**-an / -ean**, en plural **-etan**) y el verbo *egon* (**nago, dago, gaude, daude**).',
      lot:[[6, 'Los casos'], [12, 'Verbos sintéticos']],
      ar:[ { g:'Oporretan' },
        { n:'1', p:38, au:'15', m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras de las fotos', hint:ZENB(8) },
        { n:'2', p:38, pp:'38–39', m:'abc', it:L('a','f'), op:P2, pre:{ a:'1.ª' }, zer:'Aukeratu · la primera o la segunda opción', hint:BIETAKO },
        { n:'3', p:39, au:'16', m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras de las fotos', hint:ZENB(8) },
        { n:'4', p:40, au:'17', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'5', p:40, pp:'40–41', m:'abc', it:L(1,9), pre:{ '1':'c' } },
        { n:'G', p:41, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'42–47',
      lan:'Preguntar si hay algo y contestar: **badago …-(r)ik?**, **bai, badago / badaude**, **ez dago …-(r)ik**. Y *en este, en ese, en aquel*: **honetan, horretan, hartan**.',
      lot:[[15, 'La negación y el partitivo'], [4, 'Hau, hori, hura'], [12, 'Verbos sintéticos']],
      ar:[ { g:'Auzoan' },
        { n:'1', p:42, pp:'42–43', m:'tx', it:L(1,15), pre:{ '1':true }, zer:'Lotu · el número del dibujo para cada palabra', hint:'Quince palabras, por columnas de arriba abajo. Escribe el número que lleva cada sitio en el dibujo.' },
        { n:'2', p:43, m:'tx', grp:[['1.ª columna', L('a','e')], ['2.ª columna', L('a','e')]], luze:true, adib:true, zer:'Idatzi · qué hay y qué no hay en el barrio' },
        { g:'Herrian' },
        { n:'3', p:44, au:'18', m:'tx', it:L('a','d'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(4) },
        { n:'4', p:44, m:'tx', it:L('a','e'), luze:true, adib:true },
        { g:'Kalean' },
        { n:'5', p:45, m:'tx', it:L(1,16), pre:{ '1':true }, zer:'Lotu · el número del dibujo para cada palabra', hint:'Dieciséis palabras, por columnas de arriba abajo.' },
        { n:'6', p:46, au:'19', m:'mark', it:L(1,11), pre:['2'], zer:'Markatu · las cosas que se mencionan', hint:'Once palabras, por columnas de arriba abajo.' },
        { n:'7', p:46, m:'tx', it:L('a','f'), luze:true, adib:true },
        { g:'Hirian' },
        { n:'8', p:46, pp:'46–47', m:'abc', it:L(1,10), pre:{ '1':'b' } },
        { n:'9', p:47, m:'auk', it:[['', ['A', 'B']]], zer:'Aukeratu · cuál de los dos barrios es' },
        { n:'G', p:47, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'48–52',
      lan:'Situar algo o a alguien: las posposiciones de lugar (**aurrean, atzean, gainean, azpian, ondoan, artean…**), los adverbios **hemen / hor / han** y las indicaciones para llegar a un sitio.',
      lot:[[16, 'Adjetivos y posposiciones'], [4, 'Hau, hori, hura']], falta:'Las indicaciones (*segi aurrera, hartu eskuinera*) son imperativos, que todavía no están explicados en Geruzak.',
      ar:[ { g:'Umeak zaintzen' },
        { n:'1', p:48, au:'20', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'2', p:48, m:'eg', it:L('a','e'), adib:true },
        { g:'Argazkiak erakusten' },
        { n:'3', p:49, au:'21–22', m:'abc', it:L('a','j'), op:P2, pre:{ a:'1.ª' }, zer:'Entzun · la primera o la segunda opción', hint:BIETAKO },
        { n:'4', p:49, m:'tx', it:L('a','i'), luze:true, adib:true },
        { g:'Kalean galdezka' },
        { n:'5', p:50, au:'23–27', m:'tx', it:L('a','e'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(5) },
        { n:'6', p:50, m:'eg', it:L('a','d'), adib:true },
        { g:'Gidari lanetan' },
        { n:'7', p:51, au:'28–31', m:'tx', it:L('a','d'), zabal:true, pre:{ a:true }, zer:'Entzun eta osatu · con las indicaciones del recuadro', hint:'Vale el número de la indicación (1–4) o la indicación.' },
        { n:'8', p:51, pp:'51–52', m:'tx', it:L('a','d'), zabal:true, zer:'Idatzi · qué sitio es cada dibujo', hint:'A cada dibujo, uno de los cuatro sitios de la lista.' },
        { g:'Errepidean' },
        { n:'9', p:52, m:'abc', it:L(1,8), pre:{ '1':'a' } },
        { n:'G', p:52, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'53–57',
      lan:'Describir lugares: el adjetivo va detrás del nombre y es el que lleva el artículo (**etxe txikia, kale luzeak**). Además, los puntos cardinales, la hora y el tiempo que hace.',
      lot:[[3, 'El sintagma nominal'], [16, 'Adjetivos y posposiciones'], [17, 'Números, hora y calendario']],
      ar:[ { g:'Ikasle-trukea' },
        { n:'1', p:53, m:'mark', it:L(1,20), zer:'Markatu · los adjetivos que no casan con su dibujo', hint:'Veinte dibujos, por filas de cinco. En el libro, el tercero va en letra manuscrita.' },
        { n:'2', p:54, au:'32–33', m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(8) },
        { n:'3', p:54, m:'tx', it:L('a','d'), luze:true, adib:true },
        { g:'Mapan kokatzen' },
        { n:'4', p:55, pp:'54–55', m:'lib', zer:'Liburuan · subraya dónde están los países vecinos' },
        { n:'5', p:55, m:'abc', it:L('a','d'), op:P2, pre:{ a:'1.ª' }, zer:'Aukeratu · la primera o la segunda opción', hint:BIETAKO },
        { g:'Telefono elkarrizketa' },
        { n:'6', p:56, au:'34', m:'auk', it:[['1', P3], ['2', P3]], zer:'Entzun · qué hora es en cada sitio' },
        { n:'7', p:56, au:'35', m:'tx', it:L('a','f'), zabal:true, pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'8', p:56, au:'36', m:'taula', rows:L(1,8), cols:['Tokio', 'Tolosa'], pre:['0:0'], zer:'Taula · qué tiempo hace en cada sitio', hint:'Una fila por cada frase de la tabla del libro.' },
        { g:'Postala' },
        { n:'9', p:57, m:'abc', it:L(1,6), pre:{ '1':'c' } },
        { n:'G', p:57, m:'tx', it:L(1,5), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'58–59',
      lan:'Práctica de toda la unidad: contestar si hay o no hay, completar unas indicaciones sobre un plano, responder sobre un texto y describir tu pueblo o ciudad.',
      ar:[
        { n:'1', p:58, m:'tx', it:L(1,6), luze:true, zer:'Erantzun · sí o no, con la frase entera', hint:'Seis fotos, por filas.' },
        { n:'2', p:58, m:'tx', it:L('a','f'), zer:'Osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'3', p:59, m:'tx', it:L('a','h'), luze:true },
        { n:'4', p:59, m:'tx', it:L(1,13), bat:true, zer:'Idatzi · describe tu pueblo o ciudad', hint:'Una línea por pregunta del libro; la última es libre.' } ] },
    { id:'Bd', k:'Badakizu?', orr:'60',
      lan:'Autoevaluación de la unidad: ocho puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:60, m:'bai', it:L(1,8) } ] }
  ] });

  /* ── 3 · Familia eta lagunak (61–84) ─────────────────────────────────── */
  U.push({ id:'aro-03', n:3, eu:'Familia eta lagunak', orr:'61–84', atalak:[
    { id:'At', k:'Atarian', orr:'62–63',
      lan:'Los nombres de parentesco y de quién es cada uno: **noren** con nombres propios (**-(r)en**: *Ixabelen senarra*).',
      lot:[[6, 'Los casos'], [7, 'Animados y nombres propios']],
      ar:[ { g:'Ahaidetasuna' },
        { n:'1', p:62, au:'37', m:'tx', it:L('a','h'), zabal:true, pre:{ c:true }, zer:'Entzun eta idatzi · el parentesco de cada foto', hint:'Con las ocho palabras del recuadro.' },
        { n:'2', p:62, m:'tx', it:L('a','h'), adib:true, zer:'Osatu · con las palabras del recuadro', hint:ZENB(9) },
        { n:'3', p:63, au:'38', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'4', p:63, m:'abc', it:L('a','h'), op:P2, adib:true, zer:'Aukeratu · la primera o la segunda opción', hint:BIETAKO },
        { n:'G', p:63, m:'tx', it:L(1,2), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'64–69',
      lan:'Decir quién es quién, dónde vive y con quién: **noren** en nombres comunes (**-aren / -en**) y en los posesivos (*nire, zure, gure…*), **noren ondoan / atzean / artean**, *bizi izan* y **norekin** (**-arekin / -ekin**).',
      lot:[[6, 'Los casos'], [16, 'Adjetivos y posposiciones'], [9, 'IZAN']],
      ar:[ { g:'Ezkontzan' },
        { n:'1', p:64, au:'39', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'2', p:65, m:'tx', it:L('a','j'), pre:{ a:true }, zer:'Lotu · cada persona con su parentesco', hint:'Escribe el número de la frase (1–10).' },
        { g:'Lagunaren etxean' },
        { n:'3', p:65, m:'lib', zer:'Liburuan · escribe el nombre de cada persona en la foto' },
        { n:'4', p:66, m:'tx', it:L(1,6), luze:true, adib:true },
        { g:'Kafetegian' },
        { n:'5', p:66, au:'40', m:'abc', it:L('a','f'), op:P2, pre:{ a:'1.ª' }, zer:'Entzun · la primera o la segunda opción', hint:BIETAKO },
        { n:'6', p:66, m:'tx', it:L('a','g'), luze:true, adib:true },
        { g:'Sarean' },
        { n:'7', p:67, au:'41', m:'abc', it:L(1,6), pre:{ '1':'b' } },
        { n:'8', p:68, m:'eg', it:L('a','d'), adib:true },
        { g:'Aitonaren urtebetetzean' },
        { n:'9', p:68, m:'tx', it:L('a','l'), zabal:true, pre:{ a:true }, zer:'Osatu · el parentesco, según el árbol' },
        { n:'10', p:69, m:'lib', zer:'Liburuan · escribe cada nombre en su asiento' },
        { n:'11', p:69, m:'tx', it:L('a','e'), luze:true, adib:true },
        { n:'G', p:69, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'70–77',
      lan:'Describir a alguien: adjetivos de carácter y de aspecto, **nolakoa da?** (cómo es) frente a **nola dago?** (cómo está), los números del 10 al 100 y la edad con *ukan*: **nork** (**-k / -ek**) + **ditu**.',
      lot:[[10, 'UKAN'], [6, 'Los casos'], [17, 'Números, hora y calendario'], [16, 'Adjetivos y posposiciones']],
      ar:[ { g:'Lan-afarian' },
        { n:'1', p:70, m:'lib', zer:'Liburuan · subraya los adjetivos que no conoces' },
        { n:'2', p:71, au:'42', m:'tx', it:L('a','j'), pre:{ c:true }, zer:'Entzun · quién es cada persona del dibujo', hint:'Seis nombres para diez personas: escribe el número del nombre (1–6) donde toque.' },
        { n:'3', p:71, m:'tx', it:L(1,6), zabal:true, pre:{ '2':true }, zer:'Lotu · cada descripción con su persona', hint:'Escribe el nombre de la persona.' },
        { g:'Facebook-en' },
        { n:'4', p:72, m:'lib', zer:'Liburuan · subraya las palabras que no conoces' },
        { n:'5', p:72, au:'43', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun · quién es cada persona de los dibujos', hint:'Vale el número del nombre (1–6) o el nombre.' },
        { n:'6', p:73, m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'7', p:73, m:'eg', it:L('a','e'), adib:true },
        { g:'Irratian' },
        { n:'8', p:73, pp:'73–74', au:'44', m:'tx', it:L('a','l'), pre:{ a:true }, zer:'Entzun eta osatu · con los números del recuadro', hint:ZENB(12) },
        { n:'9', p:74, m:'abc', it:L(1,8), pre:{ '1':'c' } },
        { n:'10', p:74, pp:'74–76', m:'eg', it:L('a','d'), adib:true },
        { g:'DVD-an' },
        { n:'11', p:76, m:'tx', it:L('a','f'), luze:true, adib:true },
        { n:'12', p:76, m:'lib', zer:'Liburuan · di quién es cada niño del dibujo' },
        { n:'13', p:77, m:'tx', it:L('a','g'), luze:true, adib:true },
        { n:'G', p:77, m:'tx', it:L(1,6), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'78–82',
      lan:'Dar y pedir datos personales: el estado civil (**ezkondua da / ezkonduta dago**), las aficiones y las preguntas con **zenbat, nongoa, non, norekin, nolakoa, zein**. Tener o no tener: **baduzu …-(r)ik?**, **ez dut …-(r)ik**.',
      lot:[[8, 'Los interrogativos'], [15, 'La negación y el partitivo'], [10, 'UKAN']],
      ar:[ { g:'Irudia aukeratzen' },
        { n:'1', p:78, m:'lib', zer:'Liburuan · subraya las palabras que no conoces' },
        { n:'2', p:78, m:'abc', it:L('a','d'), op:L(1,4), pre:{ a:true }, zer:'Lotu · cada foto con su ficha', hint:'El número de la ficha (1–4).' },
        { g:'Lehiakideak aukeratzen' },
        { n:'3', p:79, au:'45–49', m:'tx', it:L('a','e'), pre:{ a:true }, zer:'Entzun eta osatu · con los datos del recuadro', hint:ZENB(5) },
        { n:'4', p:79, m:'taula', rows:['Esther', 'Adolfo', 'Elisa', 'Claudio', 'Pantxika'], cols:L('a','e'), pre:['0:2'], zer:'Taula · la afición de cada persona', hint:'Se hace volviendo a escuchar las pistas 45–49.' },
        { n:'5', p:80, m:'tx', it:L('a','f'), luze:true, adib:true },
        { g:'Lagunak aukeratzen' },
        { n:'6', p:80, au:'50', m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(8) },
        { n:'7', p:81, m:'eg', it:L('a','f'), adib:true },
        { g:'Bikotekidea aukeratzen' },
        { n:'8', p:81, pp:'81–82', m:'abc', it:L(1,8), pre:{ '1':'b' } },
        { n:'9', p:82, m:'idaz', zer:'Idazlana · completa la descripción', hint:'El libro da el principio de la primera frase.' },
        { n:'G', p:82, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'83',
      lan:'Práctica de toda la unidad: presentar a tu familia, explicar el parentesco, dónde vive cada uno y con quién, y describirte a ti.',
      ar:[
        { n:'1', p:83, m:'tx', grp:[['Izenak · los nombres', L('a','e')], ['Ahaidetasuna · el parentesco', L('a','e')]], bat:true, adib:true, zer:'Idatzi · tu familia: nombres y parentesco' },
        { n:'2', p:83, m:'tx', it:L('a','e'), luze:true, adib:true, zer:'Idatzi · parentesco, dónde viven y con quién' },
        { n:'3', p:83, m:'idaz', zer:'Idazlana · tu descripción', hint:'Con la ayuda de las diez preguntas del libro.' } ] },
    { id:'Bd', k:'Badakizu?', orr:'84',
      lan:'Autoevaluación de la unidad: seis puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:84, m:'bai', it:L(1,6) } ] }
  ] });

  /* ── 4 · Zure etxea (85–102) ─────────────────────────────────────────── */
  U.push({ id:'aro-04', n:4, eu:'Zure etxea', orr:'85–102', atalak:[
    { id:'At', k:'Atarian', orr:'86–87',
      lan:'Las partes de la casa y el verbo *eduki*: **daukat** con una cosa, **dauzkat** con varias. En preguntas y negaciones el nombre lleva **-(r)ik**.',
      lot:[[12, 'Verbos sintéticos'], [15, 'La negación y el partitivo']],
      ar:[ { g:'Etxea' },
        { n:'1', p:86, m:'lib', zer:'Liburuan · marca sobre los dos planos, con dos colores', oh:['A etxea', 'B etxea'] },
        { n:'2', p:87, m:'eg', it:L(1,6), adib:true },
        { n:'3', p:87, m:'auk', it:[['', P2]], zer:'Aukeratu · una de las dos casas' },
        { n:'G', p:87, m:'tx', it:L(1,2), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'88–92',
      lan:'Pedir los datos de un piso: *behar* y *nahi* con una cosa o con varias (**dut / ditut**), el precio con *balio izan* y los números a partir de 100.',
      lot:[[14, 'Nahi, behar, ahal y ari izan'], [10, 'UKAN'], [17, 'Números, hora y calendario']],
      ar:[ { g:'Anaren baserria' },
        { n:'1', p:88, au:'51', m:'tx', it:['Goiko solairua', 'Tarteko solairua', 'Beheko solairua'], zabal:true, zer:'Entzun · qué hay en cada planta', hint:'Tres, cuatro y tres huecos en el dibujo del libro.' },
        { g:'Etxe bila' },
        { n:'2', p:88, pp:'88–89', au:'52', m:'auk', it:[['a', P3], ['b', P3]] },
        { n:'3', p:89, au:'53', m:'auk', it:[['a', P3], ['b', P2]] },
        { n:'4', p:89, au:'54', m:'tx', it:L('a','e'), adib:true },
        { g:'Informazio eske' },
        { n:'5', p:90, au:'55', m:'abc', it:L(1,4), pre:{ '1':'a' } },
        { n:'6', p:90, au:'56', m:'mark', it:L('a','g'), pre:['b'], zer:'Markatu · las preguntas que oigas' },
        { n:'7', p:91, m:'lib', zer:'Liburuan · subraya en la transcripción' },
        { n:'8', p:91, au:'57', m:'auk', it:[['a', BE], ['b', P3]] },
        { g:'Pisu bila' },
        { n:'9', p:92, m:'abc', it:L(1,12), pre:{ '1':'b' } },
        { n:'G', p:92, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'93–95',
      lan:'Comparar dos casas: **-ago(a)** en adjetivos y adverbios (handiagoa, hurbilago) y **gehiago / gutxiago** con cantidades.',
      lot:[[16, 'Adjetivos y posposiciones']], falta:'*gehiago / gutxiago* todavía no está explicado en Geruzak.',
      ar:[ { g:'Etxea alokatu' },
        { n:'1', p:93, m:'auk', it:[['1.ª foto', ABC], ['2.ª foto', ABC], ['3.ª foto', ABC]], zer:'Lotu · un anuncio para cada foto' },
        { g:'Etxeak trukatu' },
        { n:'2', p:94, m:'lib', zer:'Liburuan · subraya en los dos anuncios' },
        { n:'3', p:94, m:'abc', it:L(1,6), op:['a', 'b'], pre:{ '1':'a' } },
        { g:'Etxe berria erosi' },
        { n:'4', p:95, au:'58', m:'eg', it:L(1,4), adib:true },
        { g:'Udako etxea' },
        { n:'5', p:95, m:'tx', grp:[['Donostia', L('a','e')], ['Zarautz', L('a','e')]], zer:'Osatu · con las palabras del recuadro', hint:'Diez huecos, con las diez palabras del recuadro del libro.' },
        { n:'G', p:95, m:'tx', it:L(1,2), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'96–98',
      lan:'Muebles y utensilios, habitación por habitación. Decir qué hay y qué no (**badago / ez dago …-rik**) y qué necesitas y qué no (**behar dut / ez dut …-rik behar**).',
      lot:[[15, 'La negación y el partitivo'], [14, 'Nahi, behar, ahal y ari izan']],
      ar:[ { g:'Etxetresnak' },
        { n:'1', p:96, m:'lib', zer:'Liburuan · escribe los números sobre los cuatro dibujos', hint:'Diez palabras por dibujo; la primera de cada uno ya viene hecha.' },
        { g:'Etxea jantzi' },
        { n:'2', p:97, m:'tx', it:L('a','d'), luze:true, zer:'Idatzi · una respuesta por habitación', hint:'En la a, el libro ya da la primera línea.' },
        { n:'3', p:97, au:'59', m:'taula', rows:['Luis', 'Susana', 'Luis eta Susana'], cols:L(1,6), hint:'Las columnas son los seis dibujos, de izquierda a derecha.' },
        { g:'Azoka txikia' },
        { n:'4', p:98, m:'tx', it:L(1,7), luze:true, adib:true, zer:'Idatzi · siete frases' },
        { g:'Madrilgo apartamentua' },
        { n:'5', p:98, m:'lib', zer:'Liburuan · subraya en la carta' },
        { n:'6', p:98, m:'tx', it:L(1,7), luze:true, adib:true, zer:'Idatzi · siete frases' },
        { n:'G', p:98, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'99–101',
      lan:'Práctica de toda la unidad: clasificar frases según para qué sirven, comparar dos anuncios y redactar el tuyo a partir de un plano.',
      ar:[
        { n:'1', p:99, au:'60–62', m:'auk', it:[['1', ABC], ['2', ABC], ['3', ABC]], zer:'Lotu · una situación para cada audio' },
        { n:'2', p:99, m:'tx', it:['1.º grupo', '2.º grupo', '3.º grupo', '4.º grupo'], luze:true, zer:'Sailkatu · las frases del libro en cuatro grupos', hint:'Cinco, cuatro, tres y cuatro líneas en el libro; cada grupo trae ya un ejemplo.' },
        { n:'3', p:100, m:'auk', it:[['1', ['A', 'B']], ['2', ['A', 'B']]], zer:'Lotu · anuncios y comparaciones' },
        { n:'4', p:100, m:'tx', it:[''], zabal:true },
        { n:'5', p:100, m:'tx', it:[''], zabal:true },
        { n:'6', p:100, m:'tx', it:L(1,5), luze:true, adib:true, zer:'Idatzi · cinco frases' },
        { n:'7', p:100, m:'tx', it:L(1,5), luze:true, adib:true, zer:'Idatzi · cinco frases' },
        { n:'8', p:101, m:'tx', it:L(1,10), luze:true },
        { n:'9', p:101, m:'idaz', zer:'Idazlana · redacta el anuncio' } ] },
    { id:'Bd', k:'Badakizu?', orr:'102',
      lan:'Autoevaluación de la unidad: seis puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:102, m:'bai', it:L(1,6) } ] }
  ] });

  /* ── 5 · On egin! (103–122) ──────────────────────────────────────────── */
  U.push({ id:'aro-05', n:5, eu:'On egin!', orr:'103–122', atalak:[
    { id:'At', k:'Atarian', orr:'104–105',
      lan:'Los alimentos y decir qué te gusta: *gustatu* va con **nor-nori** (**zait / zaizkit**, **zaio / zaizkio**). Lo que gusta marca el número del verbo; a quien le gusta va en **nori**.',
      lot:[[13, 'Cuando entra un tercero'], [6, 'Los casos']],
      ar:[ { g:'Janariak' },
        { n:'1', p:104, m:'tx', it:L(1,12), pre:{ '2':true }, zer:'Lotu · el número del frigorífico para cada alimento', hint:'Doce alimentos, de arriba abajo en la lista.' },
        { n:'2', p:104, au:'63', m:'mark', it:L(1,10), zer:'Markatu · los alimentos que necesitan', hint:'Diez alimentos, por filas de cinco.' },
        { n:'3', p:105, au:'64', m:'auk', it:[['porruak', BE], ['leka-patatak', BE], ['dilistak', BE], ['pasta', BE], ['sardinak', BE]], zer:'Entzun · le gusta o no le gusta', hint:'Bai = le gusta; Ez = no le gusta.' },
        { n:'4', p:105, m:'tx', it:L(1,4), luze:true, adib:true },
        { n:'G', p:105, m:'tx', it:L(1,2), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'106–110',
      lan:'Gustos y preferencias en la mesa: a quién (**nori**: **-(r)i, -ari, -ei**; *honi, horri, hari*), **gustatzen zaio / zaizkio** frente a **nahiago du / ditu**, y el orden de los platos (*lehenengo, bigarren, postrerako*).',
      lot:[[13, 'Cuando entra un tercero'], [6, 'Los casos'], [4, 'Hau, hori, hura']],
      falta:'En tu PDF faltan las páginas 108 y 109: de los ejercicios 5, 6 y 7 solo hay un recuadro libre (por la numeración, ahí van las pistas 67 y 68). *Nahiago* todavía no está explicado en Geruzak.',
      ar:[ { g:'Gosaria hotelean' },
        { n:'1', p:106, au:'65', m:'tx', it:['Lorea', 'Asier'], luze:true, zer:'Entzun · qué elige cada uno para desayunar', hint:'En el libro se marca en la lista (31 alimentos); aquí escribe lo que elige cada uno.' },
        { n:'2', p:106, m:'auk', it:[['', ['Loreari', 'Asierri']]], zer:'Aukeratu · a quién le gusta' },
        { g:'Bazkaria unibertsitatean' },
        { n:'3', p:107, au:'66', m:'taula', tx:true, rows:['1. platera', '2. platera', 'Postrea', 'Edaria'], cols:['Maite · gustatzen', 'Maite · nahiago', 'Aitor · gustatzen', 'Aitor · nahiago'],
          zer:'Taula · qué le gusta y qué prefiere cada uno', hint:'En el libro se marca con cruces (cuatro opciones en cada fila); aquí escribe el plato o los platos.' },
        { n:'4', p:107, m:'eg', it:L(1,5), adib:true },
        { n:'5', p:108, pp:'108–109', m:'tx', it:[''], luze:true, zer:'Orrialdea falta da · página que falta en tu copia' },
        { n:'6', p:108, pp:'108–109', m:'tx', it:[''], luze:true, zer:'Orrialdea falta da · página que falta en tu copia' },
        { n:'7', p:108, pp:'108–109', m:'tx', it:[''], luze:true, zer:'Orrialdea falta da · página que falta en tu copia' },
        { g:'Familia bazkaria elkartean' },
        { n:'8', p:110, m:'abc', it:L(1,12), pre:{ '1':'a' } },
        { n:'G', p:110, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'111–114',
      lan:'Dar las instrucciones de una receta: la orden más sencilla es el participio (**garbitu, zuritu, bota**); las medidas (*kilo erdi, litro bat, koilarakada bat*) y el orden de los pasos con **baino lehen / aurretik**, **bitartean**, **eta gero / ondoren** y **arte**.',
      lot:[[19, 'La subordinación']], falta:'El imperativo, *baino lehen* y *bitartean* todavía no están explicados en Geruzak.',
      ar:[ { g:'Txanpinoiak saltsan' },
        { n:'1', p:111, m:'ikus', zer:'Erreparatu · mira qué se hace en la cocina' },
        { n:'2', p:111, m:'tx', it:L(1,8), adib:true, zer:'Osatu · la receta, con los verbos del recuadro' },
        { g:'Kalabaza-krema' },
        { n:'3', p:112, au:'69', m:'tx', it:['azenario', 'tipula', 'patata', 'porru', 'baratxuri', 'ur', 'olio'], zabal:true, zer:'Entzun · qué cantidad de cada cosa', hint:'La primera cantidad la da el libro.' },
        { n:'4', p:112, au:'70', m:'abc', it:L(1,10), pre:{ '1':'a' } },
        { g:'Urdaiazpiko-kroketak' },
        { n:'5', p:113, m:'abc', it:L(1,8), op:P2, adib:true, zer:'Aukeratu · la primera o la segunda opción', hint:BIETAKO },
        { g:'Txipiroiak bere tintan' },
        { n:'6', p:114, au:'71', m:'tx', it:L(1,8), pre:{ '3':true }, zer:'Entzun eta ordenatu · el orden de cada instrucción', hint:'Ocho instrucciones, de arriba abajo: escribe su orden (1–8).' },
        { g:'Jogurt-bizkotxoa' },
        { n:'7', p:114, m:'tx', it:L(1,12), zabal:true, zer:'Osatu · la receta, con las palabras de la tabla' },
        { n:'G', p:114, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'115–118',
      lan:'Dar consejos para comer bien: la frecuencia (*egunero, astean behin, noizean behin*), **behar da / dira**, el nombre verbal **-t(z)ea** (*jatea komeni da, ona da, kaltegarria da*), la finalidad **-t(z)eko** y **eta** al final de la frase para dar la razón.',
      lot:[[14, 'Nahi, behar, ahal y ari izan'], [17, 'Números, hora y calendario'], [19, 'La subordinación']], falta:'*-t(z)ea komeni da* y el *eta* explicativo todavía no están en Geruzak.',
      ar:[ { g:'Dieta orekatua' },
        { n:'1', p:115, m:'tx', it:L(1,7), zabal:true, adib:true, zer:'Osatu · con qué frecuencia, según la pirámide' },
        { g:'Ondo jateko aholkuak' },
        { n:'2', p:116, m:'abc', op:P2, zabal:true, it:['Gosaria 1', 'Gosaria 2', 'Hamaiketakoa 1', 'Hamaiketakoa 2', 'Bazkaria 1', 'Bazkaria 2', 'Bazkaria 3', 'Askaria 1', 'Askaria 2', 'Afaria 1', 'Afaria 2', 'Afaria 3'],
          pre:{ 'Gosaria 1':'1.ª' }, zer:'Aukeratu · la primera o la segunda opción', hint:'Las parejas de opciones de cada comida, en el orden en que aparecen. ' + BIETAKO },
        { g:'Hobeto lo egiteko aholkuak' },
        { n:'3', p:117, au:'72', m:'eg', it:L(1,5), adib:true },
        { g:'Ibilaldi baterako aholkuak' },
        { n:'4', p:117, pp:'117–118', m:'tx', it:L(1,5), luze:true, adib:true },
        { g:'Umeentzako elikadura osasuntsua' },
        { n:'5', p:118, m:'abc', it:L(1,12), pre:{ '1':'b' } },
        { n:'G', p:118, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'119–121',
      lan:'Práctica de toda la unidad: reconocer los platos, pedir y rechazar comida en un diálogo, ordenar una receta y dar consejos con *-t(z)ea komeni da / kaltegarria da*.',
      ar:[
        { n:'1', p:119, m:'mark', it:L(1,11), zer:'Markatu · los platos que ha preparado', hint:'Once platos: seis en la primera columna y cinco en la segunda.' },
        { n:'2', p:119, m:'abc', it:L(1,5), op:L('a','e'), zabal:true, zer:'Osatu · una respuesta para cada hueco' },
        { n:'3', p:120, m:'abc', it:L(1,5), op:L('a','e'), zabal:true, zer:'Lotu · una instrucción para cada dibujo' },
        { n:'4', p:120, m:'tx', it:L(1,6), luze:true, adib:true },
        { n:'5', p:121, m:'abc', it:L(1,6), op:L('a','f'), zabal:true, zer:'Lotu · un consejo para cada alimento' } ] },
    { id:'Bd', k:'Badakizu?', orr:'122',
      lan:'Autoevaluación de la unidad: cinco puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:122, m:'bai', it:L(1,5) } ] }
  ] });

  /* ── 6 · Erosketak (123–142) ─────────────────────────────────────────── */
  U.push({ id:'aro-06', n:6, eu:'Erosketak', orr:'123–142', atalak:[
    { id:'At', k:'Atarian', orr:'124–125',
      lan:'Las tiendas y lo que se compra en cada una, y decir qué hay que comprar: **erosi behar dut / ditut**; en negativo, **ez dut …-(r)ik erosi behar**.',
      lot:[[14, 'Nahi, behar, ahal y ari izan'], [15, 'La negación y el partitivo']],
      ar:[ { g:'Dendak' },
        { n:'1', p:124, m:'tx', grp:[['Koldo', L(1,6)], ['Pilar', L(1,6)]], zer:'Idatzi · el nombre de cada producto', hint:'El primer producto de cada fila lo da el libro.' },
        { n:'2', p:124, m:'tx', it:['gozotegia', 'arrandegia', 'janari-denda', 'okindegia', 'harategi-urdaitegia', 'fruta-denda'], bat:true, zer:'Idatzi · qué van a comprar en cada tienda' },
        { n:'3', p:125, m:'eg', it:L(1,8), adib:true },
        { n:'4', p:125, m:'tx', it:['Nork?', 'Non?'], zabal:true },
        { n:'G', p:125, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'126–130',
      lan:'Hacer la compra: lo que se dice en el mostrador (pedir, preguntar el precio, pagar), cantidades y precios, y **erosi nahi dut / ditut**. *Nolakoa nahi duzu?* pregunta cómo lo quieres.',
      lot:[[14, 'Nahi, behar, ahal y ari izan'], [17, 'Números, hora y calendario'], [8, 'Los interrogativos']],
      ar:[ { g:'Betiko dendetan' },
        { n:'1', p:126, au:'73–74', m:'mark', it:L('a','d'), zer:'Entzun · en qué tiendas ha estado' },
        { n:'2', p:126, m:'abc', op:['M', 'S'], grp:[['1. elkarrizketa', L(1,6)], ['2. elkarrizketa', L(1,10)]], zer:'Aukeratu · quién dice cada frase', hint:'M = Martina · S = saltzailea (quien vende). Una por cada línea del diálogo.' },
        { g:'Harategi-urdaitegian' },
        { n:'3', p:127, m:'tx', it:L(1,10), pre:{ '1':true }, zer:'Osatu · una frase para cada hueco', hint:LETRA('j') },
        { g:'Merkataritza-gunean' },
        { n:'4', p:127, m:'lib', zer:'Liburuan · marca las tiendas que no conoces' },
        { n:'5', p:128, m:'tx', it:L(1,15), zer:'Idatzi · el nombre de cada producto' },
        { n:'6', p:129, au:'75', m:'abc', it:L(1,7), op:EG, pre:{ '1':'G' }, zer:EGIA },
        { n:'7', p:129, m:'tx', it:L(1,9), zabal:true, pre:{ '1':true }, zer:'Idatzi · en qué tienda se compra cada cosa' },
        { g:'Arrandegian' },
        { n:'8', p:130, m:'abc', it:L(1,12), pre:{ '1':'b' } },
        { n:'G', p:130, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'131–136',
      lan:'La ropa: los nombres de las prendas y los colores, cómo queda con **-egi** (*txikiegi, handiegi*: demasiado) y **nola dauka / dauzka**, y los gustos con **gustatzen zaio / zaizkio**.',
      lot:[[16, 'Adjetivos y posposiciones'], [12, 'Verbos sintéticos'], [13, 'Cuando entra un tercero']],
      ar:[ { g:'Asteburu luzea' },
        { n:'1', p:131, m:'lib', zer:'Liburuan · subraya las prendas que no conoces' },
        { n:'2', p:132, m:'tx', it:['Jokinen motxila', 'Oihanaren motxila'], luze:true, zer:'Idatzi · qué lleva cada uno', hint:'El libro da la primera prenda de cada mochila.' },
        { g:'Dendaz denda' },
        { n:'3', p:132, m:'abc', it:L(1,4), op:L('a','d'), pre:{ '1':'c' }, zer:'Aukeratu · cómo le queda' },
        { g:'Merkealdian' },
        { n:'4', p:133, au:'76', m:'auk', it:[['Rosa', L('a','d')], ['Nuria', L('a','d')]], zer:'Entzun · qué quiere comprar cada una' },
        { n:'5', p:133, m:'tx', it:L(1,10), pre:{ '1':true }, zer:'Ordenatu · una frase para cada hueco', hint:LETRA('j') },
        { g:'Aholkuak' },
        { n:'6', p:134, m:'abc', it:L(1,7), op:EG, pre:{ '1':'G' }, zer:EGIA },
        { g:'Gustu kontua' },
        { n:'7', p:135, au:'77', m:'taula', rows:L(1,8), cols:['Sara', 'Sergio'], zer:'Taula · qué ropa es de cada uno', hint:'Una fila por cada prenda de la tabla del libro.' },
        { n:'8', p:135, au:'78', m:'tx', it:['Josune', 'Pedro'], luze:true, zer:'Entzun eta idatzi · qué ropa le gusta', hint:'El libro da la primera línea de cada uno; quedan tres.' },
        { n:'9', p:136, m:'tx', grp:[['Sara', L(1,5)], ['Sergio', L(1,5)], ['Josune', L(1,5)], ['Pedro', L(1,5)]], bat:true, zer:'Idatzi · qué le gusta y qué no', hint:'En Sara, el libro da la 1 y la 5.' },
        { n:'G', p:136, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'137–139',
      lan:'Elegir un regalo: para quién (**norentzat**: **-arentzat, -entzat, -(r)entzat**; *niretzat, zuretzat*), por qué (**zergatik? … -(e)lako**) y las aficiones con el nombre verbal: **-t(z)ea gustatzen zaio**.',
      lot:[[5, 'La declinación: el mapa completo'], [19, 'La subordinación'], [13, 'Cuando entra un tercero']],
      ar:[ { g:'Opariak' },
        { n:'1', p:137, au:'79', m:'abc', it:L('a','e'), op:P3, pre:{ a:'3.ª' }, zer:'Entzun · una opción por pregunta' },
        { g:'Aldaketak' },
        { n:'2', p:138, au:'80', m:'abc', it:L(1,6), op:EG, pre:{ '1':'G' }, zer:EGIA },
        { g:'Lagun ezkutua' },
        { n:'3', p:138, m:'tx', it:L(1,7), pre:{ '1':true }, zer:'Lotu · para quién es cada regalo', hint:'Escribe la letra de la persona (A–G).' },
        { n:'4', p:139, m:'tx', it:L('a','f'), luze:true, adib:true, zer:'Idatzi · para quién y por qué' },
        { g:'Gabonetako opariak' },
        { n:'5', p:139, m:'abc', it:L(1,10), pre:{ '1':'a' } },
        { n:'G', p:139, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'140–141',
      lan:'Práctica de toda la unidad: un diálogo de tienda, preguntas y respuestas al comprar ropa, decir cómo queda una prenda y razonar un regalo con *-lako*.',
      ar:[
        { n:'1', p:140, m:'abc', it:L(1,5), op:L('a','e'), zabal:true, zer:'Osatu · una frase para cada hueco' },
        { n:'2', p:140, m:'auk', it:[['', P4]], zer:'Aukeratu · en qué tienda', hint:'Las cuatro fotos, de izquierda a derecha.' },
        { n:'3', p:140, m:'tx', it:L(1,7), zer:'Lotu · una respuesta para cada pregunta', hint:'Escribe la letra de la respuesta (a–g).' },
        { n:'4', p:141, m:'tx', it:L(1,4), luze:true, adib:true },
        { n:'5', p:141, m:'tx', it:L(1,4), zabal:true, zer:'Idatzi · qué prenda es', hint:'Cuatro dibujos, de izquierda a derecha.' },
        { n:'6', p:141, m:'abc', it:L('a','d'), op:P4, zabal:true, zer:'Aukeratu · qué le has dicho' },
        { n:'7', p:141, m:'tx', it:L(1,5), luze:true, adib:true, zer:'Idatzi · para quién y por qué', hint:'El ejemplo es el primer regalo; las cinco líneas son para los otros cinco.' } ] },
    { id:'Bd', k:'Badakizu?', orr:'142',
      lan:'Autoevaluación de la unidad: siete puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:142, m:'bai', it:L(1,7) } ] }
  ] });

  /* ── 7 · Zer berri? (143–163) ────────────────────────────────────────── */
  U.push({ id:'aro-07', n:7, eu:'Zer berri?', orr:'143–163', atalak:[
    { id:'At', k:'Atarian', orr:'144–145',
      lan:'Contar lo que has hecho hoy: participio + auxiliar (**jaiki naiz**, **gosaldu dut**). Los verbos intransitivos llevan *izan* y los transitivos *ukan*. En negativo el auxiliar se adelanta: **ez naiz jaiki**.',
      lot:[[11, 'El aspecto: -tu, -t(z)en, -ko'], [9, 'IZAN'], [10, 'UKAN'], [15, 'La negación y el partitivo']],
      ar:[ { g:'Jaieguna' },
        { n:'1', p:144, m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Lotu · una frase para cada dibujo', hint:ESALDI(8) },
        { n:'2', p:144, m:'tx', grp:[['Egin du · lo que ha hecho', L(1,3)], ['Ez du egin · lo que no ha hecho', L(1,3)]], bat:true, zer:'Idatzi · en dos columnas', hint:'El libro da la primera línea de cada columna.' },
        { n:'3', p:145, m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Osatu · con los verbos del recuadro', hint:'Vale el número del verbo (1–6) o el verbo.' },
        { n:'4', p:145, m:'eg', it:['a', 'b', 'c', 'd', 'f'], adib:true, hint:'En el libro, la última va con la letra f.' },
        { n:'G', p:145, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'146–150',
      lan:'Relatar lo que ha pasado hace poco: los marcadores de tiempo (*orain dela gutxi, lehentxeago, aste honetan*), ir a hacer algo con **-t(z)era** (*erostera joan da*), adónde (**nora**: -ra, -era, -etara) y de dónde (**nondik**: -tik, -etik, -etatik).',
      lot:[[6, 'Los casos'], [11, 'El aspecto: -tu, -t(z)en, -ko'], [17, 'Números, hora y calendario']],
      ar:[ { g:'Zer egin dute?' },
        { n:'1', p:146, au:'81', m:'tx', it:L('a','d'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(4) },
        { n:'2', p:146, m:'tx', it:L('a','d'), luze:true },
        { g:'Lagunekin' },
        { n:'3', p:147, m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Lotu · una frase para cada persona', hint:ESALDI(6) },
        { n:'4', p:147, m:'eg', it:L('a','e'), adib:true },
        { g:'Etxekoekin' },
        { n:'5', p:148, au:'82', m:'taula', rows:L(1,8), cols:['Goizean', 'Eguerdian', 'Arratsaldean', 'Iluntzean'], pre:['0:1'], zer:'Taula · cuándo ha hecho cada cosa', hint:'Una fila por cada frase de la tabla del libro.' },
        { g:'Egunkaria' },
        { n:'6', p:148, pp:'148–149', m:'lib', zer:'Liburuan · marca el recorrido en el mapa' },
        { n:'7', p:149, m:'tx', it:L('b','e'), luze:true, zer:'Idatzi · las etapas: de dónde adónde', hint:'La a viene resuelta en el libro.' },
        { g:'Berriak' },
        { n:'8', p:150, m:'abc', it:L(1,10), pre:{ '1':'c' } },
        { n:'G', p:150, m:'tx', it:L(1,5), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'151–154',
      lan:'Decir lo que se va a hacer: el futuro se forma con **-ko / -go** en el participio (**joango naiz**, **egingo dut**); en negativo, **ez naiz joango**. Con los marcadores *bihar, etzi, datorren astean*.',
      lot:[[11, 'El aspecto: -tu, -t(z)en, -ko'], [17, 'Números, hora y calendario']],
      ar:[ { g:'Zer egingo dute?' },
        { n:'1', p:151, au:'83', m:'auk', it:[['Maddi', L('a','d')], ['Josu', L('a','d')], ['Izaskun', L('a','d')], ['Jon', L('a','d')]], zer:'Entzun · qué foto es de cada uno' },
        { n:'2', p:152, au:'83', m:'taula', rows:L('a','h'), cols:['Josu', 'Izaskun', 'Maddi', 'Jon'], pre:['0:0'], zer:'Taula · qué va a hacer cada uno', hint:'Se hace volviendo a escuchar la misma pista.' },
        { g:'Egun-pasa Arabako Errioxan' },
        { n:'3', p:152, pp:'152–153', m:'tx', it:L(1,10), pre:{ '1':true }, zer:'Osatu · con los verbos del recuadro', hint:ADITZ('j') },
        { g:'Gonbidatuak' },
        { n:'4', p:153, au:'84', m:'tx', it:L('a','e'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(5) },
        { n:'5', p:154, m:'tx', it:L('a','e'), luze:true, adib:true },
        { g:'Bizimodu berria' },
        { n:'6', p:154, m:'abc', it:L(1,8), pre:{ '1':'b' } },
        { n:'G', p:154, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'155–159',
      lan:'Decir lo que está pasando ahora: **-t(z)en ari izan** (*idazten ari naiz*) y los verbos sintéticos *egon, joan, etorri, ibili* y *eduki* (**nago, noa, nator, nabil, daukat**).',
      lot:[[14, 'Nahi, behar, ahal y ari izan'], [12, 'Verbos sintéticos']],
      ar:[ { g:'Zertan ari dira?' },
        { n:'1', p:155, m:'abc', it:L(1,6), op:L('a','f'), zabal:true, pre:{ '1':'e' }, zer:'Lotu · un dibujo para cada frase' },
        { n:'2', p:156, m:'tx', it:L('a','e'), luze:true, adib:true },
        { g:'Giltzarik gabe' },
        { n:'3', p:156, au:'85', m:'tx', it:L('a','g'), pre:{ a:true }, zer:'Entzun eta osatu · con los verbos del recuadro', hint:'Vale el número del verbo (1–7) o el verbo.' },
        { n:'4', p:157, m:'tx', it:L('a','g'), luze:true, adib:true },
        { g:'Lagunaren zain' },
        { n:'5', p:157, au:'86', m:'abc', it:L('a','f'), op:P2, pre:{ a:'2.ª' }, zer:'Entzun · la primera o la segunda opción', hint:BIETAKO },
        { n:'6', p:158, m:'eg', it:L('a','e'), adib:true },
        { n:'7', p:158, m:'tx', it:L('a','f'), zabal:true, pre:{ a:true }, zer:'Aukeratu · un verbo del recuadro para cada dibujo' },
        { g:'Zuzeneko konexioa' },
        { n:'8', p:159, m:'abc', it:L(1,10), pre:{ '1':'c' } },
        { n:'G', p:159, m:'tx', it:L(1,4), luze:true, zer:GOGORATU, hint:'En el cuarto punto hay cinco frases para traducir.' } ] },
    { id:'E', k:'Erabili', orr:'160–162',
      lan:'Práctica de toda la unidad: preguntas sobre un texto que cuenta un viaje, verbos sintéticos en dos pies de foto, un diálogo para preparar un plan y respuestas en futuro.',
      ar:[
        { n:'1', p:160, m:'tx', it:L(1,10), luze:true },
        { n:'2', p:160, pp:'160–161', m:'tx', it:L(1,8), zer:'Osatu · con los verbos del recuadro', hint:ADITZ('h') },
        { n:'3', p:161, m:'abc', it:L(1,8) },
        { n:'4', p:162, m:'tx', it:['Adib.'].concat(L(1,7)), luze:true, zer:'Erantzun · sí o no, con la frase entera', hint:'La primera, sin número, viene empezada en el libro.' } ] },
    { id:'Bd', k:'Badakizu?', orr:'163',
      lan:'Autoevaluación de la unidad: siete puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:163, m:'bai', it:L(1,7) } ] }
  ] });

  /* ── 8 · Hau buruko mina! (165–184) ──────────────────────────────────── */
  U.push({ id:'aro-08', n:8, eu:'Hau buruko mina!', orr:'165–184', atalak:[
    { id:'At', k:'Atarian', orr:'166–167',
      lan:'Las partes del cuerpo y decir qué te duele: **-(e)ko mina** (*buruko mina, belauneko mina*; en plural **-etako**: *hanketako mina*) con **daukat / dut**.',
      lot:[[6, 'Los casos'], [12, 'Verbos sintéticos']],
      ar:[ { g:'Nongo mina' },
        { n:'1', p:166, pp:'166–167', m:'tx', it:L('a','g'), adib:true, zer:'Idatzi · la parte del cuerpo que le duele a cada uno' },
        { n:'2', p:167, m:'abc', it:L('a','g'), op:P2, adib:true, zer:'Aukeratu · la primera o la segunda opción', hint:BIETAKO },
        { n:'3', p:167, au:'87', m:'tx', it:L('a','d'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(4) },
        { n:'4', p:167, m:'tx', it:['Oskarrek', 'Sorayak'], zabal:true, zer:'Idatzi · qué le duele a cada uno' },
        { n:'G', p:167, m:'tx', it:L(1,2), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'168–171',
      lan:'Explicar los síntomas y pedir cita: **sukarra daukat**, **gaixorik nago**; la hora a la que quieres ir (**zer ordutan?** → *lauretan, ordu batean*) y lo que te manda hacer el médico, con el participio (*ireki ahoa, hartu arnasa*).',
      lot:[[12, 'Verbos sintéticos'], [17, 'Números, hora y calendario'], [14, 'Nahi, behar, ahal y ari izan']],
      ar:[ { g:'Sintomak' },
        { n:'1', p:168, m:'lib', oh:['Gripea', 'Gastroenteritisa'], zer:'Liburuan · subraya los síntomas, con dos colores' },
        { g:'Gaixorik nago' },
        { n:'2', p:169, au:'88', m:'mark', it:L(1,8), pre:['1'], zer:'Markatu · los síntomas que tiene', hint:'Ocho síntomas, por columnas de arriba abajo.' },
        { n:'3', p:169, au:'89', m:'tx', it:L(1,4), zabal:true, adib:true, zer:'Entzun eta idatzi · los síntomas que tiene' },
        { g:'Hitzordua hartu' },
        { n:'4', p:169, au:'90', m:'tx', it:L(1,5), zabal:true, zer:'Entzun eta osatu · con las frases del recuadro', hint:'Cinco huecos, en el orden de los bocadillos. La frase manuscrita del recuadro ya está usada.' },
        { g:'Medikuaren kontsultan' },
        { n:'5', p:170, au:'91', m:'eg', it:L('a','f'), adib:true },
        { n:'6', p:170, au:'92', m:'tx', it:L('a','d'), zer:'Lotu · una instrucción para cada dibujo', hint:'Escribe el número de la instrucción del recuadro (1–4, de izquierda a derecha).' },
        { n:'7', p:171, au:'93', m:'abc', it:L(1,4), pre:{ '1':'c' }, hint:'En la 1 el libro llama «d» a la tercera opción.' },
        { g:'Denak gaixorik' },
        { n:'8', p:171, m:'abc', it:L(1,8), pre:{ '1':'c' } },
        { n:'G', p:171, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'172–176',
      lan:'Dar consejos y remedios: la condición con **ba-** (**badaukazu**, *si tienes*; en negativo **ez badaukazu**), ir a donde alguien (**norengana**: **-(r)engana, -arengana, -engana**) y el resultado con el participio (*bihurritu du* → *bihurrituta dauka*).',
      lot:[[19, 'La subordinación'], [7, 'Animados y nombres propios'], [11, 'El aspecto: -tu, -t(z)en, -ko']],
      ar:[ { g:'Sendabideak' },
        { n:'1', p:172, m:'abc', it:L('a','e'), op:L(1,5), zabal:true, pre:{ a:'5' }, zer:'Lotu · un remedio para cada dolencia' },
        { n:'2', p:173, m:'tx', it:L('a','e'), zabal:true, pre:{ a:true }, zer:'Osatu · con las frases del recuadro' },
        { g:'Zauriak' },
        { n:'3', p:173, m:'lib', zer:'Liburuan · subraya las que no conoces' },
        { g:'Aholkuak' },
        { n:'4', p:174, pp:'173–174', m:'eg', it:L('a','d'), adib:true },
        { g:'Espezialistarengana' },
        { n:'5', p:174, au:'94', m:'abc', it:L(1,4), pre:{ '1':'b' } },
        { n:'6', p:175, m:'tx', it:L('a','l'), pre:{ a:true, g:true }, zer:'Osatu · con las palabras de los recuadros', hint:'Un recuadro para los huecos a–f y otro para g–l.' },
        { g:'Medikuntza alternatiboa' },
        { n:'7', p:175, au:'95–98', m:'tx', zabal:true, grp:[['2. elkarrizketa', ['Bai / Ez', 'Nongo mina', 'Norengana']], ['3. elkarrizketa', ['Bai / Ez', 'Nongo mina', 'Norengana']], ['4. elkarrizketa', ['Bai / Ez', 'Nongo mina', 'Norengana']]],
          zer:'Entzun eta osatu · la tabla', hint:'La primera conversación viene resuelta en el libro.' },
        { g:'Istripua bizikletarekin' },
        { n:'8', p:176, au:'99', m:'tx', it:L('a','d'), zabal:true, pre:{ a:true }, zer:'Entzun eta idatzi · las heridas que tiene' },
        { n:'9', p:176, m:'abc', it:L(1,8), pre:{ '1':'a' } },
        { n:'G', p:176, m:'tx', it:L(1,5), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'177–181',
      lan:'Hablar de costumbres: lo habitual se dice con **-t(z)en** + auxiliar (**joaten naiz**, **egiten dut**; en negativo **ez dut egiten**) y con la frecuencia (*egunero, askotan, batzuetan, gutxitan, inoiz ez*).',
      lot:[[11, 'El aspecto: -tu, -t(z)en, -ko'], [17, 'Números, hora y calendario'], [15, 'La negación y el partitivo']],
      ar:[ { g:'Ohitura osasuntsuak' },
        { n:'1', p:177, pp:'177–178', m:'tx', grp:[['Ohitura onak · las buenas', L(1,7)], ['Ohitura txarrak · las malas', L(1,7)]], bat:true, zer:'Idatzi · sus costumbres, en dos columnas', hint:'El libro da la primera de cada columna; no hace falta llenar todas las líneas.' },
        { g:'Astean bitan yoga' },
        { n:'2', p:178, au:'100', m:'abc', it:L(1,8), pre:{ '1':'a' } },
        { g:'Inkesta' },
        { n:'3', p:179, m:'ikus', zer:'Irakurri · las preguntas y lo que ha contestado' },
        { n:'4', p:180, m:'tx', it:['Rosak', 'Zuk'], zabal:true, zer:'Kontatu · sus puntos y los tuyos' },
        { n:'5', p:180, m:'tx', it:L('a','f'), luze:true, adib:true, zer:'Erantzun · sí o no, con la frase entera' },
        { g:'Estresa' },
        { n:'6', p:181, m:'abc', it:L(1,10), pre:{ '1':'b' } },
        { n:'G', p:181, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'182–183',
      lan:'Práctica de toda la unidad: decir qué te pasa, unir cada dolencia con su consejo, pedir cita por teléfono y contestar al médico sobre tus costumbres.',
      ar:[
        { n:'1', p:182, m:'tx', it:L('a','e'), zabal:true, adib:true, zer:'Idatzi · qué tienes en cada dibujo' },
        { n:'2', p:182, m:'abc', it:L(1,4), op:L('a','d'), zabal:true, pre:{ '1':'c' }, zer:'Lotu · un consejo para cada frase' },
        { n:'3', p:183, m:'tx', it:['a', 'b', 'c', 'izen-abizenak', 'd', 'e', 'f'], zabal:true, zer:'Osatu · la conversación por teléfono', hint:'El hueco sin letra es para tu nombre y apellidos.' },
        { n:'4', p:183, m:'tx', it:L('a','j'), luze:true, zer:'Erantzun · sí o no, con la frase entera' } ] },
    { id:'Bd', k:'Badakizu?', orr:'184',
      lan:'Autoevaluación de la unidad: siete puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:184, m:'bai', it:L(1,7) } ] }
  ] });

  /* ── 9 · Zaindu ingurumena (185–204) ─────────────────────────────────── */
  U.push({ id:'aro-09', n:9, eu:'Zaindu ingurumena', orr:'185–204', atalak:[
    { id:'At', k:'Atarian', orr:'186–187',
      lan:'Los residuos y de qué están hechos: **zerezko** (**-(e)zko**: *plastikozko botila, paperezko ahozapia*). Y lo que se puede o no se puede hacer con ellos: **bota daiteke / daitezke**, **ezin daiteke / daitezke**.',
      lot:[[6, 'Los casos']], falta:'El potencial (*daiteke, daitezke*) todavía no está explicado en Geruzak.',
      ar:[ { g:'Hondakinak' },
        { n:'1', p:186, m:'tx', it:L('a','j'), pre:{ a:true }, zer:'Lotu · una palabra para cada residuo del dibujo', hint:ZENB(10) },
        { n:'2', p:186, m:'tx', it:['1.º contenedor', '2.º contenedor', '3.º contenedor', '4.º contenedor'], luze:true, zer:'Idatzi · qué se echa en cada contenedor', hint:'Los cuatro contenedores, por filas. El primero viene empezado en el libro.' },
        { n:'3', p:187, m:'abc', it:L(1,6), op:L('a','f'), zabal:true, pre:{ '1':'d' }, zer:'Lotu · una respuesta para cada pregunta' },
        { n:'4', p:187, m:'tx', it:L(1,4), luze:true, adib:true },
        { n:'G', p:187, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'188–192',
      lan:'Dar consejos: el imperativo (**ezazu / itzazu** según el objeto sea uno o varios, **zaitez** con verbos intransitivos; para *zuek*, **ezazue, itzazue, zaitezte**), la orden contada por otro con **-t(z)eko** (*ixteko esan du*) y lo que podemos hacer: **dezaket / ditzaket**, **dezakegu / ditzakegu**.',
      lot:[[19, 'La subordinación']], falta:'El imperativo y el potencial (*dezaket, daiteke*) todavía no están explicados en Geruzak.',
      ar:[ { g:'Murriztu, berrerabili, birziklatu' },
        { n:'1', p:188, m:'taula', rows:L(1,7), cols:['Murriztu', 'Berrerabili', 'Birziklatu'], pre:['0:0'], zer:'Taula · a qué estrategia responde cada consejo', hint:'Una fila por cada consejo de la tabla del libro.' },
        { n:'2', p:188, pp:'188–189', m:'abc', it:L(1,6), op:['a', 'b'], pre:{ '1':'a' } },
        { g:'Itxi iturria' },
        { n:'3', p:189, m:'abc', it:L(1,6), op:L('a','f'), zabal:true, pre:{ '1':'d' }, zer:'Lotu · un cartel para cada dibujo' },
        { n:'4', p:189, pp:'189–190', au:'101', m:'tx', it:L(1,6), pre:{ '1':true }, zer:'Entzun eta osatu · con las frases del recuadro', hint:LETRA('f') },
        { n:'5', p:190, m:'eg', it:L(1,5), adib:true },
        { g:'Zer egin dezakegu?' },
        { n:'6', p:190, au:'102', m:'mark', it:L('a','h'), zer:'Markatu · los objetos que se mencionan' },
        { n:'7', p:191, au:'102', m:'abc', it:L('a','h'), op:L(1,4), pre:{ c:'1' }, zer:'Lotu · qué objeto se reutiliza para cada cosa', hint:'El número del objeto (1–4). Se hace volviendo a escuchar la misma pista.' },
        { g:'Garbiguneak' },
        { n:'8', p:191, pp:'191–192', m:'abc', it:L(1,8), pre:{ '1':'a' } },
        { n:'9', p:192, m:'taula', rows:L(1,4), cols:['garbigailua', 'altzariak'], zer:'Taula · qué le ha aconsejado para cada cosa', hint:'Una fila por cada frase de la tabla del libro.' },
        { n:'G', p:192, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'193–197',
      lan:'Decir lo que está prohibido y opinar: **debekatuta dago** + nombre verbal (**-t(z)ea**), **ezin da / ezin dira** + participio, y las fórmulas de opinión: **ados nago / ez nago ados**, **nire ustez**, **nire iritziz**.',
      lot:[[14, 'Nahi, behar, ahal y ari izan']], falta:'*Debekatuta dago …-t(z)ea* y las fórmulas de opinión todavía no están en Geruzak.',
      ar:[ { g:'Mendian' },
        { n:'1', p:193, m:'abc', it:L(1,6), op:L('a','f'), zabal:true, pre:{ '1':'e' }, zer:'Lotu · un significado para cada cartel' },
        { n:'2', p:193, m:'tx', it:L(1,3), bat:true, zer:'Idatzi · qué les ha dicho en cada caso', hint:'Con las tres frases del recuadro: escribe la frase o su número (1–3, de arriba abajo).' },
        { g:'Hirian' },
        { n:'3', p:194, m:'abc', it:L(1,8), op:['ezin da', 'ezin dira'], zabal:true, pre:{ '1':'ezin dira' }, zer:'Osatu · una de las dos formas' },
        { n:'4', p:194, m:'eg', it:L(1,6), adib:true },
        { g:'Hondartzan' },
        { n:'5', p:195, m:'tx', it:L(1,4), bat:true, zer:'Lotu · el significado de cada cartel', hint:'Con las cuatro frases del recuadro: escribe la frase o su número (1–4: primero la columna izquierda, de arriba abajo).' },
        { n:'6', p:195, pp:'195–196', au:'103', m:'tx', it:L(1,8), pre:{ '1':true }, zer:'Entzun eta osatu · con las expresiones del recuadro', hint:'Escribe la letra de la expresión (a–h).' },
        { n:'7', p:196, m:'tx', grp:[['Aldeko iritziak · a favor', ['1.ª norma', '2.ª norma']], ['Kontrako iritziak · en contra', ['1.ª norma', '2.ª norma']]], luze:true, zer:'Idatzi · argumentos a favor y en contra', hint:'El libro da el primer argumento a favor de cada norma.' },
        { g:'Txakurrak' },
        { n:'8', p:196, m:'abc', it:L(1,4), op:['debekatuta dago', 'ezin dira'], zabal:true, zer:'Osatu · una de las dos formas' },
        { n:'9', p:197, m:'abc', it:L(1,6), pre:{ '1':'c' } },
        { n:'G', p:197, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'198–201',
      lan:'Contar costumbres y cuándo se hacen: **-t(z)en** + auxiliar para lo habitual y **-(e)nean** para *cuando* (*garbitzen ditugunean*, *iristen denean*).',
      lot:[[11, 'El aspecto: -tu, -t(z)en, -ko'], [19, 'La subordinación']],
      ar:[ { g:'Eguzki plakak' },
        { n:'1', p:198, au:'104–107', m:'abc', it:['Martin', 'Nora', 'Pili', 'Iñaki'], op:L('a','d'), zabal:true, pre:{ Martin:true }, zer:'Entzun eta lotu · una imagen para cada persona' },
        { n:'2', p:198, au:'104–107', m:'tx', it:L('a','h'), luze:true, adib:true, hint:'Se hace volviendo a escuchar las mismas pistas.' },
        { g:'Konpromisoak' },
        { n:'3', p:199, m:'tx', it:L(1,8), pre:{ '1':true }, zer:'Bukatu · un final para cada frase', hint:LETRA('h') },
        { n:'4', p:199, m:'tx', it:L(1,7), luze:true, adib:true },
        { g:'Auzoan' },
        { n:'5', p:200, m:'abc', it:L(1,4), op:L('a','d'), pre:{ '1':'d' }, zer:'Osatu · con las formas del recuadro' },
        { n:'6', p:200, m:'tx', it:L(1,4), luze:true, adib:true },
        { n:'7', p:201, pp:'200–201', m:'eg', it:L(1,5), adib:true },
        { g:'Arropa berrerabili' },
        { n:'8', p:201, m:'abc', it:L(1,10), pre:{ '1':'a' } },
        { n:'G', p:201, m:'tx', it:L(1,2), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'202–203',
      lan:'Práctica de toda la unidad: reconocer los residuos, decir dónde se echa cada cosa, dar consejos, indicar adónde llevar lo que no se recicla y redactar carteles de prohibición.',
      ar:[
        { n:'1', p:202, m:'mark', it:L(1,10), zer:'Markatu · los residuos que aparecen en el dibujo', hint:'Diez residuos, de arriba abajo en la lista.' },
        { n:'2', p:202, m:'abc', it:L(1,6), op:['ezin da', 'ezin dira', 'bota ezazu', 'bota itzazu'], zabal:true, zer:'Osatu · una de las cuatro formas' },
        { n:'3', p:202, m:'tx', it:L(1,5), luze:true, adib:true, zer:'Osatu · qué consejo le darías' },
        { n:'4', p:203, m:'abc', it:L(1,6), pre:{ '1':'a' } },
        { n:'5', p:203, m:'tx', it:L('a','d'), zabal:true, pre:{ a:true }, zer:'Osatu · las malas costumbres, con el verbo que se da' },
        { n:'6', p:203, m:'tx', it:L(1,4), zabal:true, zer:'Osatu · los carteles, con las formas del recuadro' } ] },
    { id:'Bd', k:'Badakizu?', orr:'204',
      lan:'Autoevaluación de la unidad: ocho puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:204, m:'bai', it:L(1,8) } ] }
  ] });

  /* ── 10 · Herria ala hiria? (205–224) ────────────────────────────────── */
  U.push({ id:'aro-10', n:10, eu:'Herria ala hiria?', orr:'205–224', atalak:[
    { id:'At', k:'Atarian', orr:'206–207',
      lan:'Describir un lugar diciendo que es *el más…*: el superlativo, **-(r)ik …-en(a)(ak)** (*hiririk jendetsuena*, *festarik ospetsuenak*), y sus formas irregulares (**onena, gehien, ondoen, txarrena, gutxien, okerren**).',
      lot:[[16, 'Adjetivos y posposiciones']], falta:'Las formas irregulares del superlativo todavía no están en Geruzak. Estas dos páginas no están en el PDF del libro entero, pero sí en el de la unidad suelta.',
      ar:[ { g:'Hiriburuak' },
        { n:'1', p:206, m:'tx', it:L('a','f'), zabal:true, pre:{ a:true }, zer:'Osatu · con las expresiones del recuadro', hint:'Vale el número de la expresión (1–6) o la expresión.' },
        { n:'2', p:206, m:'taula', rows:['Bilbo', 'Gasteiz', 'Iruñea', 'Baiona'], cols:L('a','h'), zer:'Taula · a qué ciudad se refiere cada nota' },
        { n:'3', p:207, m:'abc', it:L(1,6), pre:{ '1':'c' } },
        { n:'G', p:207, m:'tx', it:L(1,2), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'208–212',
      lan:'Comparar dos sitios: la cualidad con **baino …-ago(a)(ak)** (*Bilbo baino handiagoa*), la cantidad con **baino … gehiago / gutxiago**, las formas irregulares (*hobea, hobeto, okerrago*) y, cuando no se dice con qué se compara, **hain** + adjetivo y **hainbeste** + nombre.',
      lot:[[16, 'Adjetivos y posposiciones']], falta:'*gehiago / gutxiago*, *hain* y *hainbeste* todavía no están explicados en Geruzak.',
      ar:[ { g:'Bizilekua' },
        { n:'1', p:208, m:'abc', it:L('a','h'), op:['Pablo', 'Nagore'], pre:{ a:'Pablo', c:'Nagore' }, zer:'Sailkatu · de quién es cada argumento', hint:'En el libro se copian en dos columnas; aquí marcas de quién es cada uno.' },
        { g:'Herritik hiri handira' },
        { n:'2', p:209, au:'108', m:'abc', it:L(1,6), op:P2, zer:'Entzun · la primera o la segunda opción', hint:BIETAKO },
        { n:'3', p:210, m:'eg', it:L('a','e'), adib:true },
        { g:'Auzo berria' },
        { n:'4', p:210, au:'109', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'5', p:211, m:'abc', it:L('a','f'), op:['hain', 'hainbeste'], zabal:true, pre:{ a:'hainbeste' }, zer:'Osatu · una de las dos partículas' },
        { g:'Hiritik herrira' },
        { n:'6', p:211, pp:'211–212', m:'abc', it:L(1,8), pre:{ '1':'b' } },
        { n:'7', p:212, m:'tx', it:L(1,6), luze:true, adib:true },
        { n:'G', p:212, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'213–216',
      lan:'Dar tu opinión y contar la de otros: la frase completiva con **-(e)la** (*ona dela uste dut*) detrás de **uste dut**, **pentsatzen dut**, **iruditzen zait** y **esan du**. El sufijo cambia según cómo acabe el verbo: **-la**, **-ela** o **-dala** (*dut* → *dudala*).',
      lot:[[19, 'La subordinación'], [13, 'Cuando entra un tercero']],
      ar:[ { g:'Mahai-ingurua' },
        { n:'1', p:213, au:'110', m:'abc', it:L('a','d'), op:L(1,4), pre:{ a:'2' }, zer:'Entzun eta osatu · una expresión para cada hueco', hint:'El número de la expresión (1–4).' },
        { n:'2', p:214, m:'tx', it:['a', 'b'], luze:true, adib:true, zer:'Osatu · cuenta lo que ha dicho cada uno' },
        { g:'Ikasleen iritzia' },
        { n:'3', p:214, m:'ikus', zer:'Irakurri · los apuntes con la opinión de cada alumno' },
        { n:'4', p:214, pp:'214–215', m:'eg', it:L('a','d'), adib:true },
        { g:'Herri txikien arazoa' },
        { n:'5', p:215, m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Osatu · el resumen, con las expresiones del recuadro', hint:'Escribe el número de la expresión (1–8).' },
        { g:'Herritarren balorazioa' },
        { n:'6', p:216, m:'abc', it:L(1,10), pre:{ '1':'a' } },
        { n:'G', p:216, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'217–220',
      lan:'Gustos y preferencias para las vacaciones: la comparación en negativo (**ez da … baino …-agoa**, **ez dago … baino … gehiago**), **nahiago dut** y el nombre verbal con *gustatu*: **-t(z)ea gustatzen zait**, siempre en singular.',
      lot:[[16, 'Adjetivos y posposiciones'], [13, 'Cuando entra un tercero']], falta:'*Nahiago* todavía no está explicado en Geruzak.',
      ar:[ { g:'Londresera ala Erromara?' },
        { n:'1', p:217, au:'111', m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Entzun eta osatu · un argumento para cada hueco', hint:'Escribe el número del argumento (1–8).' },
        { n:'2', p:218, m:'tx', it:L('a','c'), luze:true, adib:true },
        { g:'Udako oporrak' },
        { n:'3', p:218, m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Osatu · con las palabras del recuadro', hint:ZENB(6) },
        { n:'4', p:218, m:'eg', it:L('a','d'), adib:true },
        { n:'5', p:219, m:'tx', it:L('a','f'), luze:true, adib:true },
        { g:'Oporrak etxean' },
        { n:'6', p:219, au:'112–114', m:'abc', it:L(1,6), pre:{ '1':'c' }, zer:'Entzun · a quién corresponde cada frase', hint:'a, b y c son las tres escenas del dibujo.' },
        { g:'Mendira ala hondartzara?' },
        { n:'7', p:220, m:'abc', it:L(1,8), pre:{ '1':'b' } },
        { n:'G', p:220, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'221–223',
      lan:'Práctica de toda la unidad: deducir qué pueblo es cada uno a partir de unas comparaciones, comparar el tuyo, contestar una encuesta sobre tu localidad, opinar con *-(e)la* y decir qué prefieres para viajar.',
      ar:[
        { n:'1', p:221, m:'tx', it:L('a','c'), zabal:true, zer:'Lotu · qué pueblo es cada columna de la tabla' },
        { n:'2', p:221, m:'tx', bat:true, adib:true, grp:[['Zure herria · los datos de tu pueblo', ['Biztanleria', 'Tabernak', 'Elizak', 'Museoak', 'Zinemak eta antzokiak', 'Osasun-zentroak', 'Botikak', 'Eskolak eta ikastolak']], ['Konparazioak · compáralo', L('a','g')]],
          zer:'Osatu eta konparatu · tu pueblo o ciudad' },
        { n:'3', p:222, m:'tx', bat:true, it:['Tamaina', 'Merkataritza', 'Lana', 'Etxebizitza', 'Osasun-zerbitzuak', 'Garraioak eta komunikazioa', 'Kirola', 'Hezkuntza-eskaintza', 'Kultura', 'Ingurumena', 'Kaleko giroa', 'Eguraldia'],
          zer:'Erantzun · la encuesta sobre tu localidad', hint:'En el libro se marcan casillas. Aquí escribe, en cada apartado, el número de la opción o las opciones que marcas, contando de arriba abajo.' },
        { n:'4', p:223, m:'idaz', zer:'Idazlana · tu opinión, frase a frase', hint:'Una frase por cada respuesta marcada en el ejercicio 3. El libro da tres de ejemplo.' },
        { n:'5', p:223, m:'tx', it:L('a','h'), luze:true } ] },
    { id:'Bd', k:'Badakizu?', orr:'224',
      lan:'Autoevaluación de la unidad: siete puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:224, m:'bai', it:L(1,7) } ] }
  ] });

  /* ── 11 · Lan eta lan (225–248) ──────────────────────────────────────── */
  U.push({ id:'aro-11', n:11, eu:'Lan eta lan', orr:'225–248', atalak:[
    { id:'At', k:'Atarian', orr:'226–228',
      lan:'Los oficios, los idiomas y lo que sabes: el verbo *jakin* (**dakit** con una cosa, **dakizkit** con varias; **badakit**, **ez dakit**) y saber hacer algo: **-t(z)en jakin** (*gidatzen badakit*).',
      lot:[[12, 'Verbos sintéticos'], [14, 'Nahi, behar, ahal y ari izan']],
      ar:[ { g:'Bideocurriculuma' },
        { n:'1', p:226, au:'115–118', m:'tx', it:L('a','d'), pre:{ a:true }, zer:'Entzun · el oficio de cada persona', hint:'Escribe el número del oficio (1–10).' },
        { n:'2', p:226, au:'119', m:'abc', it:L('a','h'), op:L(1,3), pre:{ a:'2' }, zer:'Entzun eta osatu · una forma para cada hueco', hint:'El número de la forma (1–3).' },
        { n:'3', p:227, au:'120', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las frases del recuadro', hint:ESALDI(6) },
        { n:'4', p:227, m:'eg', it:L('a','e'), adib:true },
        { n:'5', p:228, m:'abc', it:L(1,9), pre:{ '1':'a' } },
        { n:'G', p:228, m:'tx', it:L(1,5), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'229–234',
      lan:'Dar y pedir información sobre un trabajo: para dónde es (**norako**: **-(e)rako, -etarako**), los nombres de los trabajos (*begirale-lana*), el verbo con tres participantes **nor-nori-nork** (**diot, dizkiot, didazu, digu…**) y el vocabulario de los anuncios de empleo.',
      lot:[[13, 'Cuando entra un tercero'], [5, 'La declinación: el mapa completo']],
      ar:[ { g:'Sosak ateratzen' },
        { n:'1', p:229, m:'ikus', zer:'Erreparatu · lee las ofertas de trabajo' },
        { n:'2', p:229, au:'121', m:'tx', it:L('a','e'), pre:{ a:true }, zer:'Entzun eta osatu · con las palabras del recuadro', hint:ZENB(5) },
        { n:'3', p:230, m:'tx', it:L('b','e'), luze:true, zer:'Lotu eta idatzi · el trabajo más adecuado para cada uno', hint:'La a viene resuelta en el libro, y la b empezada.' },
        { g:'Trukea' },
        { n:'4', p:231, au:'122–124', m:'tx', it:L(1,12), pre:{ '1':true, '5':true, '9':true }, zer:'Entzun eta osatu · con las formas del recuadro', hint:'Tres recuadros de cuatro formas, uno para cada pareja de textos.' },
        { n:'5', p:232, m:'tx', it:L(1,6), luze:true, adib:true },
        { g:'Egun osoko lanaldia' },
        { n:'6', p:232, m:'ikus', zer:'Irakurri · los anuncios: qué piden y qué ofrecen' },
        { n:'7', p:233, au:'125', m:'auk', it:[['', L('a','c')]], zer:'Entzun · a qué anuncio ha llamado' },
        { n:'8', p:233, m:'abc', it:L('a','g'), op:P2, adib:true, zer:'Aukeratu · la primera o la segunda opción', hint:BIETAKO },
        { g:'Lan berria' },
        { n:'9', p:234, m:'abc', it:L(1,8), pre:{ '1':'b' } },
        { n:'G', p:234, m:'tx', it:L(1,5), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'235–239',
      lan:'Valorar cualidades y habilidades: los adjetivos de carácter, **badakizu …-t(z)en?** y la pregunta indirecta, con **-(e)n** en el verbo (*zenbat urte dituzun galdetu du*) y **ea** cuando no lleva interrogativo. El sufijo es **-n**, **-en** o **-dan** (*dut* → *dudan*).',
      lot:[[19, 'La subordinación'], [12, 'Verbos sintéticos'], [8, 'Los interrogativos']],
      ar:[ { g:'Lan-eskaintzak' },
        { n:'1', p:235, au:'126–131', m:'tx', it:L('a','i'), pre:{ a:true }, zer:'Entzun eta osatu · una cualidad para cada hueco', hint:'Escribe el número de la cualidad (1–9).' },
        { n:'2', p:236, m:'eg', it:L('a','d'), adib:true },
        { g:'Lan-elkarrizketa' },
        { n:'3', p:236, au:'132', m:'abc', it:L(1,6), op:['komeni da', 'ez da komeni'], zabal:true, pre:{ '1':'komeni da' }, zer:'Entzun · qué conviene hacer y qué no', hint:'Las seis filas de las dos tablas: primero la de la izquierda, de arriba abajo.' },
        { n:'4', p:237, au:'133', m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Entzun eta osatu · con los verbos del recuadro', hint:'Vale el número del verbo (1–8) o el verbo.' },
        { n:'5', p:237, m:'tx', it:L(1,4), luze:true, adib:true },
        { g:'Zer galdetu dizute?' },
        { n:'6', p:238, m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Osatu · con las palabras del recuadro', hint:ZENB(8) },
        { n:'7', p:238, au:'134', m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Entzun eta osatu · con los verbos del recuadro', hint:'Vale el número del verbo (1–8) o el verbo.' },
        { g:'Lankide berria' },
        { n:'8', p:239, m:'abc', it:L(1,10), pre:{ '1':'a' } },
        { n:'G', p:239, m:'tx', it:L(1,6), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'240–245',
      lan:'Contar la experiencia en un trabajo: de quién has aprendido (**norengandik**: **-(r)engandik, -a(ren)gandik, -engandik**), aprender y enseñar a hacer algo (**-t(z)en ikasi / irakatsi**) y lo bueno y lo malo de cada oficio.',
      lot:[[7, 'Animados y nombres propios'], [13, 'Cuando entra un tercero'], [11, 'El aspecto: -tu, -t(z)en, -ko']],
      ar:[ { g:'Lanbide zaharrak' },
        { n:'1', p:240, au:'135', m:'tx', it:L('a','h'), pre:{ a:true }, zer:'Entzun eta idatzi · el oficio de cada puesto', hint:'Vale el número del oficio (1–8) o su nombre.' },
        { n:'2', p:241, au:'136', m:'abc', it:L('a','f'), op:P2, zer:'Entzun · la primera o la segunda opción' },
        { g:'Alde onak eta txarrak' },
        { n:'3', p:242, m:'tx', bat:true, grp:[['a · alde onak', L(1,3)], ['a · alde txarrak', L(1,3)], ['b · alde onak', L(1,3)], ['b · alde txarrak', L(1,3)], ['c · alde onak', L(1,3)], ['c · alde txarrak', L(1,3)], ['d · alde onak', L(1,3)], ['d · alde txarrak', L(1,3)]],
          zer:'Idatzi · lo bueno y lo malo de cada trabajo', hint:'En la a, el libro da la primera línea de cada lista.' },
        { g:'Denon eskola' },
        { n:'4', p:243, au:'137', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con los verbos del recuadro', hint:'Vale el número del verbo (1–6) o el verbo.' },
        { n:'5', p:244, m:'tx', it:L('b','f'), luze:true, zer:'Lotu eta idatzi · una frase por persona', hint:'La a viene resuelta en el libro.' },
        { g:'Emakume artzaina' },
        { n:'6', p:244, pp:'244–245', m:'abc', it:L(1,12), pre:{ '1':'b' } },
        { n:'G', p:245, m:'tx', it:L(1,6), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'246–247',
      lan:'Práctica de toda la unidad: decir qué jornada, horario y contrato te convienen, completar tu currículum y redactar lo que dirías en un vídeo, preparar una entrevista y describir tu trabajo.',
      ar:[
        { n:'1', p:246, m:'tx', it:['Lanaldia · komeni', 'Lanaldia · gustatzen', 'Ordutegia · komeni', 'Ordutegia · nahiago', 'Kontratua · komeni'], bat:true, zer:'Erantzun · qué te conviene y qué prefieres' },
        { n:'2', p:247, m:'tx', bat:true, grp:[['Curriculuma · tus datos', L(1,8)], ['Grabatzeko testua · lo que vas a decir', ['']]], zer:'Osatu eta idatzi · tu currículum y el texto del vídeo' },
        { n:'3', p:247, m:'tx', it:L(1,12), luze:true, zer:'Erantzun · las preguntas de una entrevista', hint:'Doce preguntas, de arriba abajo.' },
        { n:'4', p:247, m:'idaz', zer:'Idazlana · describe tu trabajo', hint:'Con la ayuda de las ocho preguntas del libro.' } ] },
    { id:'Bd', k:'Badakizu?', orr:'248',
      lan:'Autoevaluación de la unidad: siete puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:248, m:'bai', it:L(1,7) } ] }
  ] });

  /* ── 12 · Aisialdia (249–272) ────────────────────────────────────────── */
  U.push({ id:'aro-12', n:12, eu:'Aisialdia', orr:'249–272', atalak:[
    { id:'At', k:'Atarian', orr:'250–251',
      lan:'Las actividades de ocio y cuándo se hacen: el día con **-(e)an** (*asteartean*) y, si es todas las semanas, en plural con **-etan** (*astelehenetan*); de qué hora a qué hora con **-etatik … -etara** (*bostetatik zazpietara*).',
      lot:[[17, 'Números, hora y calendario'], [6, 'Los casos']],
      ar:[ { g:'Kultura eskaintza' },
        { n:'1', p:250, au:'138', m:'tx', it:['Izaskun', 'Miren', 'Andoni', 'Jon', 'Arantxa'], zabal:true, pre:{ Miren:true }, zer:'Entzun · qué actividad ha elegido cada uno' },
        { n:'2', p:250, au:'139', m:'lib', oh:['Miren', 'Andoni'], zer:'Liburuan · marca en el horario lo que eligen' },
        { n:'3', p:251, m:'abc', it:L(1,4), pre:{ '1':'b' } },
        { n:'4', p:251, m:'tx', it:L('a','d'), luze:true, adib:true },
        { n:'G', p:251, m:'tx', it:L(1,3), luze:true, zer:GOGORATU } ] },
    { id:'A', k:'A', orr:'252–256',
      lan:'Dar y pedir información sobre un plan: cómo se va (**zerez**: *autobusez, trenez, oinez*), en qué mes (**-(e)an**: *martxoan*), en qué fecha (**ekainaren 24an**) y hasta dónde (**noraino**: **-(e)raino**).',
      lot:[[17, 'Números, hora y calendario'], [6, 'Los casos']], falta:'**-(e)raino** (*hasta*) todavía no está explicado en Geruzak.',
      ar:[ { g:'Kobetamendi' },
        { n:'1', p:252, au:'140', m:'mark', it:['autobusez', 'autoz', 'itsasontziz', 'taxiz', 'bizikletaz', 'oinez', 'motoz', 'metroz', 'trenez', 'tranbiaz'], zer:'Markatu · cómo recomiendan ir' },
        { n:'2', p:252, m:'eg', it:L('a','d'), adib:true },
        { g:'Erretiratuen elkartea' },
        { n:'3', p:253, pp:'253–254', m:'tx', it:L('a','l'), pre:{ a:true }, zer:'Osatu · el mes de cada salida', hint:'Escribe el número del mes del recuadro (1–12).' },
        { n:'4', p:254, au:'141', m:'tx', it:L('a','d'), pre:{ a:true }, zer:'Entzun eta osatu · con las fechas del recuadro', hint:'Vale el número de la fecha (1–4) o la fecha.' },
        { g:'Euskaltegiko irteera' },
        { n:'5', p:255, m:'tx', it:L('a','i'), pre:{ a:true, i:true }, zer:'Ordenatu · el recorrido, pueblo a pueblo' },
        { n:'6', p:255, m:'tx', it:L('a','g'), pre:{ a:true }, zer:'Osatu · con las palabras del recuadro', hint:ZENB(7) },
        { g:'Zirkura' },
        { n:'7', p:256, m:'abc', it:L(1,12), pre:{ '1':'b' } },
        { n:'G', p:256, m:'tx', it:L(1,5), luze:true, zer:GOGORATU } ] },
    { id:'B', k:'B', orr:'257–262',
      lan:'Proponer planes: lo que apetece (**-t(z)eko gogoa daukat / dut**) y lo que se piensa hacer (**-t(z)eko asmoa**), con **gogorik / asmorik** en preguntas y negaciones; los porcentajes (**% 20**, *ehuneko hogei*) y la condición con **ba-** (*eguraldi ona egiten badu*).',
      lot:[[14, 'Nahi, behar, ahal y ari izan'], [19, 'La subordinación'], [15, 'La negación y el partitivo']],
      falta:'*-t(z)eko asmoa* y los porcentajes todavía no están en Geruzak.',
      ar:[ { g:'Erlaxatzeko gogoa' },
        { n:'1', p:257, au:'142–147', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con las frases del recuadro', hint:ESALDI(6) },
        { n:'2', p:258, m:'tx', it:L('a','e'), luze:true, adib:true },
        { n:'3', p:258, m:'tx', it:L('a','d'), luze:true, adib:true, zer:'Erantzun · sí o no, con la frase entera' },
        { g:'Ikasleen asmoak' },
        { n:'4', p:259, au:'148', m:'tx', it:L('a','g'), zabal:true, zer:'Entzun eta osatu · con las frases del recuadro', hint:'Ocho frases para ocho huecos; la manuscrita ya está puesta en el primero, que no lleva letra.' },
        { n:'5', p:260, m:'eg', it:L('a','e'), adib:true },
        { n:'6', p:260, m:'tx', it:L('b','e'), luze:true, zer:'Osatu · la leyenda del gráfico', hint:'La a viene resuelta en el libro.' },
        { g:'Ikasturte bukaerako bazkaria' },
        { n:'7', p:261, au:'149', m:'tx', it:L('a','f'), pre:{ a:true }, zer:'Entzun eta osatu · con los verbos del recuadro', hint:'Vale el número del verbo (1–6) o el verbo.' },
        { n:'8', p:261, m:'tx', grp:[['Aldeko argudioak · a favor', L('a','d')], ['Kontrako argudioak · en contra', L('a','d')]], luze:true, adib:true, zer:'Idatzi · argumentos a favor y en contra' },
        { g:'Sendaviva' },
        { n:'9', p:262, m:'abc', it:L(1,10), pre:{ '1':'a' } },
        { n:'G', p:262, m:'tx', it:L(1,6), luze:true, zer:GOGORATU } ] },
    { id:'C', k:'C', orr:'263–268',
      lan:'Contar costumbres de ahora y de antes: lo habitual con **-t(z)en** + auxiliar, en presente (**joaten naiz**) y en pasado (**joaten nintzen**). Para eso hacen falta *izan* y *ukan* en pasado: **nintzen, zen, ginen**; **nuen, zuen, genuen**.',
      lot:[[11, 'El aspecto: -tu, -t(z)en, -ko'], [9, 'IZAN'], [10, 'UKAN']],
      ar:[ { g:'Udako oporrak' },
        { n:'1', p:263, m:'abc', it:L(1,12), pre:{ '1':'c' } },
        { n:'2', p:264, m:'tx', it:L('a','h'), luze:true, adib:true },
        { g:'Amona Manoli' },
        { n:'3', p:264, pp:'264–265', au:'150', m:'tx', it:L('a','l'), pre:{ a:true }, zer:'Entzun eta osatu · con los verbos del recuadro', hint:'Vale el número del verbo (1–12) o el verbo.' },
        { n:'4', p:265, m:'tx', grp:[['Iratik · ahora', ['c', 'e', 'g', 'i', 'k']], ['Amonak · antes', ['d', 'f', 'h', 'j', 'l']]], luze:true, zer:'Idatzi · qué hace ella y qué hacía la abuela', hint:'La a y la b vienen resueltas en el libro.' },
        { g:'Eta udan, zer?' },
        { n:'5', p:266, pp:'266–267', m:'abc', it:L('a','f'), op:L(1,6), zabal:true, pre:{ a:'3' }, zer:'Lotu · una imagen para cada propuesta' },
        { n:'6', p:267, m:'mark', it:L(1,12), pre:['3'], zer:'Markatu · las propuestas que se mencionan', hint:'Doce propuestas: seis en la primera columna y seis en la segunda.' },
        { g:'Ohitura berriak' },
        { n:'7', p:268, m:'tx', it:L('a','j'), pre:{ a:true }, zer:'Osatu · con los verbos del recuadro', hint:'Vale el número del verbo (1–10) o el verbo.' },
        { n:'8', p:268, m:'tx', it:L('a','k'), luze:true, adib:true },
        { n:'G', p:268, m:'tx', it:L(1,4), luze:true, zer:GOGORATU } ] },
    { id:'E', k:'Erabili', orr:'269–271',
      lan:'Práctica de toda la unidad: tu agenda de la semana con días y horas, decir qué te apetece, contar un plan de viaje con fechas, transporte y recorrido, y lo que hacías de pequeño en vacaciones.',
      ar:[
        { n:'1', p:269, m:'ikus', zer:'Erreparatu · la agenda y lo que hace en su tiempo libre' },
        { n:'2', p:269, m:'tx', it:L('a','d'), luze:true, zer:'Idatzi · qué haces tú de lunes a viernes' },
        { n:'3', p:270, m:'ikus', zer:'Irakurri · qué le apetece y qué no' },
        { n:'4', p:270, m:'tx', it:L('a','f'), luze:true, zer:'Erantzun · sí o no, con la frase entera' },
        { n:'5', p:270, m:'ikus', zer:'Erreparatu · el mapa y el plan' },
        { n:'6', p:271, m:'tx', it:['Non', 'Noiz', 'Norekin', 'Zer egiteko asmoa', 'Zer', 'Nondik noraino', 'Nola', 'Noiz atera', 'Noiz itzuli'], bat:true, zer:'Osatu · el texto con tu plan', hint:'Un hueco por cada dato, en el orden del texto del libro.' },
        { n:'7', p:271, m:'ikus', zer:'Irakurri · qué hacía de pequeño en vacaciones' },
        { n:'8', p:271, m:'idaz', zer:'Idazlana · qué hacías tú de pequeño', hint:'Con la ayuda de las siete preguntas del libro.' } ] },
    { id:'Bd', k:'Badakizu?', orr:'272',
      lan:'Autoevaluación de la unidad: ocho puntos, cada uno con Bai o Ez.',
      ar:[ { n:'', p:272, m:'bai', it:L(1,8) } ] }
  ] });

  window.LIBURUAK = window.LIBURUAK || {};
  window.LIBURUAK.arian = { src:'arian', izena:'Arian A1', taldea:'Unitateak', unitateak:U };
})();
